### PR TITLE
Add descriptions for methods

### PR DESCRIPTION
**Pull request by janczer**
Add descriptions for Goby Api Documentation

@adlerhsieh Check it, please.

### CODE REVIEW

**Comment by st0012** [comment]
@adlerhsieh You can merge this after review it

**Comment by adlerhsieh** [comment]
@st0012 It says I'm not authorized to merge this pull request. Maybe there's a permission configuration?

**Comment by st0012** [comment]
@adlerhsieh Try again?

**Comment by adlerhsieh** [comment]
Nope, still not working.

screen shot 2017-05-27 at 1 32 19 pm

It links to [this page](https://help.github.com/articles/about-protected-branches/) so probably something related to this.

**Comment by st0012** [comment]
Sorry but can you try again? I changed other settings.

**Comment by adlerhsieh** [comment]
Yes it works. Thanks.

**Pull request merged**
