### PR TITLE
Add to contribution how add new method

### PR DESCRIPTION
**Pull request by janczer**

### CODE REVIEW

**Comment by st0012** [comment]
@janczer Fixed some grammar errors and rebased

**Comment by janczer** [comment]
@st0012 If everything ok, can you merge it?

**Comment by st0012** [comment]
@janczer I'm just thinking to move this and other detailed contribution guides into wiki, and just putting links here. Otherwise this file will be too long to read in the future. What do you think?

**Comment by janczer** [comment]
@st0012 I think add it to wiki good idea.

**Comment by adlerhsieh** [comment]
Hi I've used your code and add a wiki page. You could check if everything is good and modify at will.

https://github.com/goby-lang/goby/wiki/Contibuting-a-Method

**Comment by janczer** [comment]
@adlerhsieh Everything is ok, thank you!

**Comment by st0012** [comment]
@janczer so can you change the content to the link to wiki?

**Comment by adlerhsieh** [comment]
The link is already in the doc. We can probably close this one.

**Comment by st0012** [comment]
@adlerhsieh Ok, next time you can just close it 😄

**Pull request closed without merging**
