### PR TITLE
Fix #560 & #561

### LINKED ISSUE #560: Leading `;` causes a panic
When the line is started with `;`, the following panic is occurred.

```ruby
» ;
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x40f99fa]

goroutine 1 [running]:
github.com/goby-lang/goby/compiler/bytecode.(*Generator).compileExpression(0xc4201aefc0, 0xc4201da000, 0x0, 0x0, 0xc4201af050, 0xc4201b0640)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/bytecode/expression_generation.go:9 +0x3a
github.com/goby-lang/goby/compiler/bytecode.(*Generator).compileStatement(0xc4201aefc0, 0xc4201da000, 0x4820240, 0xc42000c080, 0xc4201af050, 0xc4201b0640)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/bytecode/statement_generation.go:40 +0x334
github.com/goby-lang/goby/compiler/bytecode.(*Generator).compileStatements(0xc4201aefc0, 0xc420052050, 0x1, 0x1, 0xc4201af050, 0xc4201b0640)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/bytecode/statement_generation.go:22 +0xd0
github.com/goby-lang/goby/compiler/bytecode.(*Generator).GenerateInstructions(0xc4201aefc0, 0xc420052050, 0x1, 0x1, 0x1, 0xc42001c110, 0xd)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/bytecode/generator.go:54 +0x5b
github.com/goby-lang/goby/igb.StartIgb(0x457257f, 0x5)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/igb/repl.go:229 +0xcf4
main.main()
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/goby.go:29 +0x954
```

### LINKED ISSUE #561: Empty files causes a panic
If Goby runs an empty file (or only LFs contained), the following panic causes:

```bash
$ goby 50sandbox.gb # empty file
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/goby-lang/goby/compiler/bytecode.(*Generator).compileStatements(0xc420061d80, 0x48767c8, 0x0, 0x0, 0xc420089200, 0xc4200f4860)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/bytecode/statement_generation.go:25 +0x27b
github.com/goby-lang/goby/compiler/bytecode.(*Generator).GenerateInstructions(0xc420061d80, 0x48767c8, 0x0, 0x0, 0xc4200891d0, 0xc42000e030, 0xc420061db0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/bytecode/generator.go:54 +0x5b
github.com/goby-lang/goby/compiler.CompileToInstructions(0x0, 0x0, 0x0, 0x200, 0x0, 0x0, 0x7ffeefbfe467, 0x2)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/compiler.go:34 +0x1e0
main.main()
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/goby.go:60 +0x303
```

Looks like the issue is related to #560.

### PR DESCRIPTION
**Pull request by st0012**
This closes #560 and closes #561

### CODE REVIEW

**Comment by hachi8833** [comment]
#561 still needs fix. The following is an evaluation test for that:

```go
func TestEmptyCodeEvaluation(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{``, ""},
		{`
`, ""},
	}

	for i, tt := range tests {
		v := initTestVM()
		evaluated := v.testEval(t, tt.input, getFilename())

		if isError(evaluated) {
			t.Fatalf("got Error: %s", evaluated.(*Error).message)
		}

		verifyExpected(t, i, evaluated, tt.expected)
		v.checkCFP(t, i, 0)
		v.checkSP(t, i, 1)
	}
}
```

**Comment by st0012** [comment]
@hachi8833 I've tried that. We can't test that in current testing approach, because the parser will have different mode and behavior under test environment. And the issue you mentioned is a test-mode-only issue.

**Comment by hachi8833** [comment]
Got it

**Comment by st0012** [comment]
@hachi8833 Do you approve this PR?

**Pull request merged**
