### PR TITLE
Hash to json

### PR DESCRIPTION
**Pull request by st0012**
Just like `Hash#to_json` in Rails, example:
```ruby
h = { a: 1, b: [1, "2", [4, 5, nil], { foo: "bar" }]}.to_json
puts(h) #=> {"a":1,"b":[1, "2", [4, 5, null], {"foo":"bar"}]}
```

### CODE REVIEW

**Comment by st0012** [comment]
BTW I can't use string for test comparison because Go's map (which we use to store key/value pairs) is random ordered. So we might get different result string every time.

**Comment by hachi8833** [comment]
Got an error with the following that contains capitalized key(yes, not so good):

```ruby
h = { Ocean:  { Squid: 10, Octopus: 8 }}.to_json
puts(h)
```

> panic: expected next token to be IDENT, got CONSTANT instead. Line: 0
expected next token to be }, got CONSTANT instead. Line: 0
no prefix function for :. Line: 0
expected next token to be IDENT, got CONSTANT instead. Line: 0
expected next token to be }, got CONSTANT instead. Line: 0
no prefix function for :. Line: 0
no prefix function for ,. Line: 0
no prefix function for :. Line: 0
no prefix function for }. Line: 0
no prefix function for }. Line: 0
no prefix function for .. Line: 0

But the following works:

```ruby
ruby
h = { oCean:  { sqUid: 10, ocTopus: 8 }}.to_json
puts(h)
```

**Comment by st0012** [comment]
@hachi8833 well that's not `to_json`'s issue. It's because we haven't support constants as hash's key,  can you open an issue for this and I or @hachi8833  will open another PR to deal with it.

**Comment by st0012** [comment]
If there's no other issues, I'm going to merge this~

**Pull request merged**
