### PR TITLE
Added tests for goby command

### PR DESCRIPTION
**Pull request by ear7h**
This test file runs a goby binary in the repository's root directory and compares the output to expected outputs.

### CODE REVIEW

**Comment by st0012** [comment]
@ear7h Can you make CI pass?

**Comment by st0012** [comment]
@ear7h Can you rebase it instead of merge master?

**Comment by ear7h** [comment]
@st0012 I'm not sure what you mean... I saw some that the branch was out of date and couldn't merge, would you like me to start from a new branch? The only real changes for this PR live in the goby_test.go file

**Comment by st0012** [comment]
@ear7h Sorry plz ignore that comment, for some reason I saw there's hundreds of change files when I left it.

**Pull request merged**
