### PR TITLE
Implement Hash#each

### PR DESCRIPTION
**Pull request by saveriomiroddi**
In order to facilitate testing, the testing API `testBidimensionalArrayObject` has been added.

### CODE REVIEW

**Comment by st0012** [comment]
@saveriomiroddi LGTM, but can you add some simple comments on the `testBidimensionalArrayObject` function?

**Comment by saveriomiroddi** [comment]
> LGTM, but can you add some simple comments on the testBidimensionalArrayObject function?

Done! I've also add a new test case.

**Comment by saveriomiroddi** [comment]
@st0012 b7146b800ec126b6cfedaa227d5d242863e58097 adds a new testing API that is better suited to test code involving (resulting in) Hashes. If you wish, I can cherry-pick that commit and update this PR's unit tests to use it, although, the tests as they are now, are valid and readable.

**Comment by st0012** [comment]
@saveriomiroddi You can cherry-pick that commit I think

**Comment by saveriomiroddi** [comment]
> You can cherry-pick that commit I think
@st0012 ok. I've cherry picked the commit, and updated the UTs to use the hash testing API.

**Comment by saveriomiroddi** [comment]
@st0012 conflicts solved, by rebasing.

**Pull request merged**
