### PR TITLE
#355 Fix String Excaped Character

### PR DESCRIPTION
**Pull request by Maxwell-Alexius**

### CODE REVIEW

**Comment by Maxwell-Alexius** [comment]
This PR aims to fix #355

**Comment by st0012** [comment]
@Maxwell-Alexius Can you also add vm tests (just like lexer's)? Because this string might be changed during this process `AST->bytecode->VM's value`

**Comment by Maxwell-Alexius** [comment]
Is it sth like string test which have escaped characters?

_Sent from my Htc HTC_D728x using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by st0012** [comment]
@Maxwell-Alexius Yes, it's better to add new test cases to every string function tests. And you don't have to add every escape cases I think, just focus on `\"` and `\'`

**Comment by Maxwell-Alexius** [comment]
Updated!

**Pull request merged**
