### PR TITLE
Implement Module(Class)#>

### PR DESCRIPTION
**Pull request by kachick**
If the direction is not wrong, I can add `#<` , `#>=`, `#<=` in other PR .

### CODE REVIEW

**Comment by hachi8833** [comment]
LGTM.
@st0012 How about this?

**Comment by st0012** [comment]
@kachick @hachi8833 I think this could be added, but we'll need more complex test cases. For example: 

```ruby
module Foo; end
class Bar; end

Object > Foo #=> nil
Object < Foo #=> nil
Bar > Foo #=> false
Bar < Foo #=> true
```

**Comment by st0012** [comment]
Can you find related ruby specs from [Ruby Spec](https://github.com/ruby/spec)?

**Comment by kachick** [comment]
Of sorry, perfectly forgotten to compare with non related modules 🙇 
Applied it in https://github.com/goby-lang/goby/pull/512/commits/5417218a5db6d48c4fa9968ac53ebebfa61fbd7b

**Comment by kachick** [comment]
Thank you! ☺️

**Pull request merged**
