### PR TITLE
#182 Implementing Fundamental Range API

### PR DESCRIPTION
**Pull request by Maxwell-Alexius**
Currently struggling on implementing the `Range#bsearch` method, other methods are just fine.

### CODE REVIEW

**Comment by st0012** [comment]
@Maxwell-Alexius Looks Can you also add some test cases for ranges that contain negative number? After that this should be ready to merge.

**Comment by Maxwell-Alexius** [comment]
Yes, will do!

**Comment by Maxwell-Alexius** [comment]
Tips: In Ruby 2.4.1, `range#step` do not accept negative step value, and it will only loop in ascending range.

Remark: If decide to implement negative step feature, feel free to discuss it or open another PR. For now, this PR implementing `range#step` do not accept negative step.

**Comment by st0012** [comment]
@Maxwell-Alexius I see, current behavior is sufficient for most cases I guess. So is this ready to merge?

**Comment by Maxwell-Alexius** [comment]
Yep, ready. (Almost forgot to remove WIP label off)

**Pull request merged**
