### PR TITLE
Refactor method definitions in vm/ for readability

### PR DESCRIPTION
**Pull request by hachi8833**
I hope this change might be good this time.

### CODE REVIEW

**Comment by st0012** [comment]
Moving method name up is a good idea, but I'm not sure if this would effect document generation. @adlerhsieh can you check this?

**Comment by adlerhsieh** [comment]
Currently it will not effect the parser, although the style might need some tweak. If putting `Name` above `Fn`, then the comment for this method still needs to come right above `Fn`. For example:

```go
var builtinIntegerMethods = []*BuiltInMethod{
  {
    Name: "+",
    // Returns the sum of self and another Integer.
    Fn: func(receiver Object) builtinMethodBody {
      // ...
    },
}
```

But we're still in an early stage so changing this style won't take too much time. Comments can come either above `Name` or  bracket `{`.

**Comment by st0012** [comment]
@adlerhsieh I think you can decide the style, although I prefer comment upon the name.

**Comment by hachi8833** [comment]
Updated my master branch with the style as adlerhsieh suggested.
(I was just wondering how to update the PR yesterday)

**Comment by adlerhsieh** [comment]
To update a PR, just push to the branch again. In you case, push to `master` will do. 

However, some general guidelines to follow if you want to keep contributing:

- Checkout to a new branch when working on a new feature. When opening a PR, it means your things are stuck with that branch. Sometimes a PR could take a week of discussion before merge. If you have something new in mind, you won't be able to progress if you always work on `master`. In your case, modifying `Integer#prev` including 0688a04a5288e4f72b69910e608de232b0aa064f and c836f7466e89652bc5cacbb3c9d687edfb6e1160 are not related to this PR.
- Use `git commit --amend` and `git push --force` to overwrite commits. If you add a line and commit, and after discussion you add another line and commit. In my experience doing this 10 times in a PR is common, and it makes the commits very dirty. It's better to overwrite the same stuff.

**Comment by hachi8833** [comment]
Sorry, I should've PR with a new feature branch, instead of merging to my local master branch. I'll be careful next time.

**Pull request merged**
