### PR TITLE
Add a compile option to reduce binary size

### PR DESCRIPTION
**Pull request by hachi8833**
Just a small change to reduce Goby's binary size.

### CODE REVIEW

**Comment by st0012** [comment]
@hachi8833 I remember we can use compiled binary to run tests in Go, can you help checking that? If so, I want to use the reduced sized binary to run tests

**Comment by hachi8833** [comment]
The option to reduce binary size works on `make test`.

**Comment by st0012** [comment]
@hachi8833 Can you apply these flags into `travis.sh`'s test commands?

**Comment by hachi8833** [comment]
I did. I hope this works.

**Comment by hachi8833** [comment]
I think CI runs faster now. Merging...

**Pull request merged**
