### PR TITLE
colors on Windows

### PR DESCRIPTION
**Pull request by mattn**
* colors on Windows
* strict path for temporary directory
* disable emoji(s)

windows

### CODE REVIEW

**Comment by st0012** [comment]
Hello @mattn, thanks for pointed out these issues 🙇

**Comment by st0012** [comment]
Looks like there's a dependency issue, would you mind fixing it?

**Comment by mattn** [comment]
Yes please.

**Comment by mattn** [comment]
Ah, sorry, I'll do it soon.

**Comment by st0012** [comment]
@mattn Thank you 😄

**Comment by mattn** [comment]
Do you use package manager? AFAICS, just put vendor direcotory. RIght?

**Comment by st0012** [comment]
We use `godep`

**Comment by st0012** [comment]
@mattn Would you mind I open a new branch and PR to solve the issue you met.?

**Comment by mattn** [comment]
yes, please. I'm not master of godep.

**Pull request closed without merging**
