### PR TITLE
Implementing auto-indentation in REPL

### PR DESCRIPTION
**Pull request by hachi8833**
I'm a bit stucked: how do I redraw the previous line on unindentation.

170716_0729_dvhdlw

Looks like the current [readline](https://github.com/chzyer/readline) package has no api to redraw the previous line (or might be I looked over). In addition, the document is too short.

Looking at [commit log](https://github.com/chzyer/readline/pulls), the package has not been updated for months while [some PRs](https://github.com/chzyer/readline/pulls) remain.

Controlling readline is pretty hard because the behavior often depends on terminal and OS environments.

Any suggestion?

### CODE REVIEW

**Comment by hachi8833** [comment]
Found a way to do that!

```go
		rl.Config.UniqueEditLine = true
		line, err := rl.Readline()
		rl.Config.UniqueEditLine = false
```

I'd try more

**Comment by st0012** [comment]
It seems that readline is not a large project, we can fork our own version if necessary. We can work on it together.(You may also  join their maintenance team 😆)

**Comment by st0012** [comment]
BTW you can take REPL as a topic for lightning talk

**Comment by hachi8833** [comment]
Auto-indentation implementation finished!

**Comment by st0012** [comment]
LGTM, you can merge this once you think it's ready
And can you record how it performs now and paste it here?

**Comment by hachi8833** [comment]
Thanks! I'd merge by myself.
https://asciinema.org/a/8mMW0Amc77gkWYAQ97WqeoxFw

**Pull request merged**
