### PR TITLE
Lazy Enumerator, with lazy array enumeration

### PR DESCRIPTION
**Pull request by saveriomiroddi**
Basic implementation of a lazy enumerator, with Array support for it via Array#lazy.

Requires #572, ~#566~, #578.

### CODE REVIEW

**Comment by st0012** [comment]
@saveriomiroddi #566 is merged now!

**Comment by st0012** [comment]
@saveriomiroddi I think all blocking PR have been merged now

**Comment by saveriomiroddi** [comment]
@st0012 ready :smile:

**Comment by st0012** [comment]
@saveriomiroddi LGTM

Will our next step be supporting lazy enumerator on range? I think it'll be important as well and can show the power of lazy evaluation more.

```ruby
module Enumerable
  def filter_map(&block)
    map(&block).compact
  end
end

class Enumerator::Lazy
  def filter_map
    Lazy.new(self) do |yielder, *values|
      result = yield *values
      yielder << result if result
    end
  end
end

(1..10000).lazy.filter_map{|i| i*i if i.even?}.first(5)
    # => [4, 16, 36, 64, 100]
```

(I know the code will look differently, but I think we should be able to achieve this, right?

**Comment by saveriomiroddi** [comment]
> Will our next step be supporting lazy enumerator on range? I think it'll be important as well and can show the power of lazy evaluation more.

Yes. The conventional showcase for lazy evaluation uses `Float::INFINITY`:

```ruby
(1..Float::INFINITY).lazy.map { |i| 2*i }.first(5) # => [2, 4, 6, 8, 10]
```

Because examples of the type:

```ruby
(1..10000).lazy.map { |i| i*i if i.even? }.first(5)       # example via :map, as Ruby has no :filter_map
```

don't give an obvious difference in an example run; using Float::INFINITY will hang without lazy iterator.

**Comment by saveriomiroddi** [comment]
In order to implement lazy range enumeration, a RangeEnumerator will need to implemented, which has the methods `#next` and `#has_next?`.

**Comment by st0012** [comment]
@saveriomiroddi So if there's any good showcase for Array's lazy evaluation?

**Comment by saveriomiroddi** [comment]
> So if there's any good showcase for Array's lazy evaluation?

Not really, in fact, when I showcased or tested, I used either a conditional error raise, or an accumulation array (with check). Possibly the conditional error raise is the best:

    [0, 1, 2].lazy.map { |n| n >= 2 ? raise : n }.first(2)

In general, lazy evaluation is always shown with a range (and infinity), however this also shows clearly lazy evaluation (although it's somewhat unconventional).

**Pull request merged**
