### PR TITLE
Exclude incorrectly parsed files from codeclimate checks

### PR DESCRIPTION
**Pull request by saveriomiroddi**
Due to CC not currently supporting Go 1.9 syntax, some files are not parsed correctly, and cause CC to fail.

### CODE REVIEW

**Comment by saveriomiroddi** [comment]
@st0012 I'm not sure why CC fails on this PR. I've tested the change in my fork, and it yields green. 

Feel free to close this PR without merging if you think CC should still run on those two files :smile: 

I think it would be better to skip the checks on those 2 files (and revert the change when CC is fixed), since they don't add any value, and make the PR status red.

**Comment by st0012** [comment]
I think I'll just wait for codeclimate to fix that issue, so I don't plan to change its config file. I'll check every PR's other CI status so it doesn't matter CC is red.

**Comment by st0012** [comment]
@saveriomiroddi And I think you shouldn't include other PR's change (like this), in other PRs

**Comment by saveriomiroddi** [comment]
> And I think you shouldn't include other PR's change (like this), in other PRs

Sorry, it was accidental - I tried it in master because CC was only testing my master branch, and not the other PRs.

I've now removed it from everywhere.

**Pull request closed without merging**
