### PR TITLE
Added Line() function to all AST nodes

### PR DESCRIPTION
**Pull request by Heasummn**
Closes issue #37

### CODE REVIEW

**Comment by st0012** [comment]
@Heasummn Can you please add some tests for this change? thanks 😄

**Comment by st0012** [comment]
@Heasummn Hi, If you want your branch's base up to date, you should update master branch to the latest commit, and then checkout to this branch and `rebase master`. Merging master branch is not a good practice unless you have good reason for doing it~

**Comment by hzlmn** [comment]
```golang
func (_ *Program) Line() int {
 	// The program always starts at line 1
	return 1
 }
```
I think it is wrong as lexer support skipping whitespaces program can start not exactly on 1 line.
@st0012  Isn't it?

**Comment by st0012** [comment]
@hzlmn Agree, we need to consider that there would be some files contain some empty lines before the first line of code. @Heasummn Can you help change that and add some test in `parser` package? thx

**Comment by st0012** [comment]
@Heasummn Hi, are you still working on this?

**Pull request closed without merging**
