### PR TITLE
#200 Reordering VM API Methods

### PR DESCRIPTION
**Pull request by Maxwell-Alexius**
This PR aims to refactor the VM methods in alphabetical ordering

### CODE REVIEW

**Comment by Maxwell-Alexius** [comment]
Currently I do not sort the String methods in this PR because it may cause me more time to rebase branch #184 if this branch should merge with String API sorted

**Comment by st0012** [comment]
LGTM, but I think it would be safer to let others check again. @hachi8833 can you help review it again?

**Comment by hachi8833** [comment]
I looked through briefly and LGTM, too.
(It'd be better if the commits were smaller chunks by class)

**Comment by st0012** [comment]
@hachi8833 thanks!

**Pull request merged**
