### PR TITLE
Fix #589

### LINKED ISSUE #589: Class#singleton_class needs a feature to create a singleton class when it does not have one
I found that current `Class#singleton_class` causes panic when applying to objects other than classes:

```ruby
Goby 0.1.7 😍 😺 🤤
» "a".singleton_class
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x43d1b35]

goroutine 1 [running]:
github.com/goby-lang/goby/vm.(*RClass).toString(0x0, 0xc4201c2a80, 0xffffffffffffffff)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/class.go:1205 +0x5
github.com/goby-lang/goby/vm.(*VM).GetREPLResult(0xc4200a6820, 0xc42000ea88, 0x1)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/repl.go:73 +0x4e
github.com/goby-lang/goby/igb.StartIgb(0x4577b0d, 0x5)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/igb/repl.go:233 +0xd34
main.main()
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/goby.go:29 +0x954
```

According to http://devdocs.io/ruby~2.5/object#method-i-singleton_class:

> Returns the singleton class of obj. This method creates a new singleton class if obj does not have one.

The feature to create a new singleton class is missing in current Goby.

### PR DESCRIPTION
**Pull request by hachi8833**
This fixes #589.

Note that the fix works against even Integer objects like `1` (Ruby cannot do that).
I hope this works.

### CODE REVIEW

**Comment by st0012** [comment]
@hachi8833 good job!

**Comment by hachi8833** [comment]
TravisCI reported the following error: this has been fixed by st0012.
I just wonder the accuracy of float/decimal depends on environments...

```
--- FAIL: TestDecimalArithmeticOperationWithFloat (0.14s)
	vm_test.go:276: At test case 8: object has wrong value. expect=21.257317715840923000314433011226356029510498046875, got=21.257317715840930105741790612228214740753173828125
	vm_test.go:276: At test case 9: object has wrong value. expect=21.257317715840923000314433011226356029510498046875, got=21.257317715840930105741790612228214740753173828125
```

**Comment by st0012** [comment]
@hachi8833 shout out when you finish this

**Comment by hachi8833** [comment]
TravisCi test has been passed! This can be merged.

**Pull request merged**
