### PR TITLE
Improve error report

### PR DESCRIPTION
**Pull request by st0012**
This PR is try to use panic/recover mechanism to do error report, instead of actively checking if stack's  top value is an error object.

### CODE REVIEW

**Comment by st0012** [comment]
@saveriomiroddi Sorry, I actually want you to review this. I'll keep polishing the panic raising part, but I think you can see what I intend to do already.

**Comment by st0012** [comment]
@saveriomiroddi This is pretty much finished, can you help me review it?

**Comment by saveriomiroddi** [comment]
Hello! I've just finished reviewing now. I don't have experience with Go patterns, but this looks ok as error throwing/catching pattern.

**Comment by st0012** [comment]
@saveriomiroddi Yes that's what I try to do, thanks!

**Pull request merged**
