### PR TITLE
Refactor: Replace Go's slow regexp to strings.Replace

### PR DESCRIPTION
**Pull request by hachi8833**
Actually, the improvement of performance is trivial.

### CODE REVIEW

**Comment by st0012** [comment]
But the code does become simpler 😁

**Comment by st0012** [comment]
@hachi8833  Should I use Github update branch and merge it?

**Comment by hachi8833** [comment]
Go ahead 😄

**Comment by st0012** [comment]
BTW you can just add refactoring label next time, I think you are able to do this

**Comment by hachi8833** [comment]
I got it; I'd try the label next time

**Pull request merged**
