### PR TITLE
Update demo screen

### PR DESCRIPTION
**Pull request by hachi8833**
Used the official way to embed the asciinema movie as follows:

[asciicast](https://asciinema.org/a/sVOfdRmG3QyxQTrRMNVhjlYKo)

(GitHub does not permit to embed directly on Readme)

### CODE REVIEW

**Comment by hachi8833** [comment]
Converted the asciinema movie to animated gif:

<iframe src="https://giphy.com/embed/KzPAERGFY99EZHOMNQ" width="480" height="331" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/KzPAERGFY99EZHOMNQ">via GIPHY</a></p>

I will apply this instead.

**Comment by st0012** [comment]
@hachi8833 so is this done or? I prefer using gif directly

**Comment by hachi8833** [comment]
Creating and uploading a big animated-gif is pretty hard...
I also prefer to the direct gif and try it again soon.

**Comment by st0012** [comment]
@hachi8833 I think we can upload a 30 secs gif and provide the full length link?

**Comment by hachi8833** [comment]
@st0012 Sorry for the delay. You can check the updated preview of README:

https://github.com/goby-lang/goby/blob/cb7c3982c0258b544996f7723823f128424cb025/README.md

**Pull request merged**
