### PR TITLE
Enhancement of VM Array and String API

### PR DESCRIPTION
**Pull request by Maxwell-Alexius**

### CODE REVIEW

**Comment by Maxwell-Alexius** [comment]
@st0012 It seems the `instruction.go` let codeclimate encounters the error

**Comment by st0012** [comment]
@Maxwell-Alexius That's because we have used some Go 1.9's feature and codeclimate haven't upgrade their linter. Already opened a ticket to them few days ago.

**Comment by st0012** [comment]
LGTM, is this ready for merge?

**Comment by Maxwell-Alexius** [comment]
Yes, you may!

**Pull request merged**
