### PR TITLE
Continuous fuzzing

### PR DESCRIPTION
**Pull request by bookmoons**
Hi guys. What about integrating fuzzing? [Fuzzit](https://fuzzit.dev/) gives free service for open source.

This patch fuzzes `CompileToInstructions()`. A local run found some crashes. I'll post them in a comment.

Build will fail because due to missing an API key. If you're interested setup is like this:
* In Fuzzit create target `goby`.
* In Fuzzit settings grab an API key. In repo settings in [Travis](https://travis-ci.org/) paste it to an envvar `FUZZIT_API_KEY`.

### CODE REVIEW

**Comment by bookmoons** [comment]
Here's the crash data. Also posting some examples of the panics.

[crashers.zip](https://github.com/goby-lang/goby/files/3533335/crashers.zip)

```
_,t.a
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4bc92d]

goroutine 1 [running]:
github.com/goby-lang/goby/compiler/ast.(*BaseNode).Line(0x0, 0x0)
	/home/user/go/src/github.com/goby-lang/goby/compiler/ast/ast.go:16 +0x1d
github.com/goby-lang/goby/compiler/bytecode.(*Generator).compileExpression(0xc000049df0, 0xc0000a8000, 0x55ba60, 0xc00000c120, 0xc00000c160, 0xc00000c140)
	/home/user/go/src/github.com/goby-lang/goby/compiler/bytecode/expression_generation.go:13 +0x9a
github.com/goby-lang/goby/compiler/bytecode.(*Generator).compileCallExpression(0xc000049df0, 0xc0000a8000, 0xc000058120, 0xc00000c160, 0xc00000c140)
	/home/user/go/src/github.com/goby-lang/goby/compiler/bytecode/expression_generation.go:102 +0x171
github.com/goby-lang/goby/compiler/bytecode.(*Generator).compileExpression(0xc000049df0, 0xc0000a8000, 0x55b520, 0xc000058120, 0xc00000c160, 0xc00000c140)
	/home/user/go/src/github.com/goby-lang/goby/compiler/bytecode/expression_generation.go:63 +0xd65
github.com/goby-lang/goby/compiler/bytecode.(*Generator).compileStatement(0xc000049df0, 0xc0000a8000, 0x55b6a0, 0xc00000c0a0, 0xc00000c160, 0xc00000c140)
	/home/user/go/src/github.com/goby-lang/goby/compiler/bytecode/statement_generation.go:38 +0x487
github.com/goby-lang/goby/compiler/bytecode.(*Generator).compileStatements(0xc000049df0, 0xc0000103a0, 0x1, 0x1, 0xc00000c160, 0xc00000c140)
	/home/user/go/src/github.com/goby-lang/goby/compiler/bytecode/statement_generation.go:22 +0x119
github.com/goby-lang/goby/compiler/bytecode.(*Generator).GenerateInstructions(0xc000049df0, 0xc0000103a0, 0x1, 0x1, 0xc000000180, 0x200000003, 0xc000000180)
	/home/user/go/src/github.com/goby-lang/goby/compiler/bytecode/generator.go:43 +0x77
github.com/goby-lang/goby/compiler.CompileToInstructions(0xc00008ee88, 0x5, 0x1, 0x5, 0xc00008ee88, 0x5, 0x5d5f7ff3, 0xc00008eea8)
	/home/user/go/src/github.com/goby-lang/goby/compiler/compiler.go:22 +0x33e
github.com/goby-lang/goby/compiler.Fuzz(0x764d7f267000, 0x5, 0x5, 0x4)
	/home/user/go/src/github.com/goby-lang/goby/compiler/compiler_fuzz.go:10 +0x89
go-fuzz-dep.Main(0xc000049f80, 0x1, 0x1)
	/tmp/go-fuzz-build858729003/goroot/src/go-fuzz-dep/main.go:36 +0x1b6
main.main()
	/tmp/go-fuzz-build858729003/gopath/src/github.com/goby-lang/goby/compiler/go.fuzz.main/main.go:15 +0x52
exit status 2
```

---

```
d 0=0
```

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/goby-lang/goby/compiler/bytecode.(*Generator).compileCallExpression(0xc000049df0, 0xc0000a8050, 0xc000058240, 0xc00000c1e0, 0xc00000c1c0)
	/home/user/go/src/github.com/goby-lang/goby/compiler/bytecode/expression_generation.go:110 +0xcab
github.com/goby-lang/goby/compiler/bytecode.(*Generator).compileExpression(0xc000049df0, 0xc0000a8050, 0x55b520, 0xc000058240, 0xc00000c1e0, 0xc00000c1c0)
	/home/user/go/src/github.com/goby-lang/goby/compiler/bytecode/expression_generation.go:63 +0xd65
github.com/goby-lang/goby/compiler/bytecode.(*Generator).compileStatement(0xc000049df0, 0xc0000a8050, 0x55b6a0, 0xc00000c180, 0xc00000c1e0, 0xc00000c1c0)
	/home/user/go/src/github.com/goby-lang/goby/compiler/bytecode/statement_generation.go:38 +0x487
github.com/goby-lang/goby/compiler/bytecode.(*Generator).compileStatements(0xc000049df0, 0xc0000107a0, 0x1, 0x1, 0xc00000c1e0, 0xc00000c1c0)
	/home/user/go/src/github.com/goby-lang/goby/compiler/bytecode/statement_generation.go:22 +0x119
github.com/goby-lang/goby/compiler/bytecode.(*Generator).GenerateInstructions(0xc000049df0, 0xc0000107a0, 0x1, 0x1, 0xc000000180, 0x200000003, 0xc000000180)
	/home/user/go/src/github.com/goby-lang/goby/compiler/bytecode/generator.go:43 +0x77
github.com/goby-lang/goby/compiler.CompileToInstructions(0xc000049e88, 0x5, 0x1, 0x5, 0xc000049e88, 0x5, 0x5d5f7f9f, 0xc000049ea8)
	/home/user/go/src/github.com/goby-lang/goby/compiler/compiler.go:22 +0x33e
github.com/goby-lang/goby/compiler.Fuzz(0x77c82ec6a000, 0x5, 0x5, 0x3)
	/home/user/go/src/github.com/goby-lang/goby/compiler/compiler_fuzz.go:10 +0x89
go-fuzz-dep.Main(0xc000049f80, 0x1, 0x1)
	/tmp/go-fuzz-build858729003/goroot/src/go-fuzz-dep/main.go:36 +0x1b6
main.main()
	/tmp/go-fuzz-build858729003/gopath/src/github.com/goby-lang/goby/compiler/go.fuzz.main/main.go:15 +0x52
exit status 2
```

---

```
d 0%v:0
```

```
panic: interface conversion: ast.Expression is *ast.InfixExpression, not *ast.Identifier

goroutine 1 [running]:
github.com/goby-lang/goby/compiler/bytecode.(*Generator).compileCallExpression(0xc000049df0, 0xc0000ac0a0, 0xc000058480, 0xc00000c420, 0xc00000c400)
	/home/user/go/src/github.com/goby-lang/goby/compiler/bytecode/expression_generation.go:113 +0xc73
github.com/goby-lang/goby/compiler/bytecode.(*Generator).compileExpression(0xc000049df0, 0xc0000ac0a0, 0x55b520, 0xc000058480, 0xc00000c420, 0xc00000c400)
	/home/user/go/src/github.com/goby-lang/goby/compiler/bytecode/expression_generation.go:63 +0xd65
github.com/goby-lang/goby/compiler/bytecode.(*Generator).compileStatement(0xc000049df0, 0xc0000ac0a0, 0x55b6a0, 0xc00000c3c0, 0xc00000c420, 0xc00000c400)
	/home/user/go/src/github.com/goby-lang/goby/compiler/bytecode/statement_generation.go:38 +0x487
github.com/goby-lang/goby/compiler/bytecode.(*Generator).compileStatements(0xc000049df0, 0xc000010ff0, 0x1, 0x1, 0xc00000c420, 0xc00000c400)
	/home/user/go/src/github.com/goby-lang/goby/compiler/bytecode/statement_generation.go:22 +0x119
github.com/goby-lang/goby/compiler/bytecode.(*Generator).GenerateInstructions(0xc000049df0, 0xc000010ff0, 0x1, 0x1, 0xc000000180, 0x200000003, 0xc000000180)
	/home/user/go/src/github.com/goby-lang/goby/compiler/bytecode/generator.go:43 +0x77
github.com/goby-lang/goby/compiler.CompileToInstructions(0xc000049e88, 0x7, 0x1, 0x7, 0xc000049e88, 0x7, 0x5d5f7f97, 0xc000049ea8)
	/home/user/go/src/github.com/goby-lang/goby/compiler/compiler.go:22 +0x33e
github.com/goby-lang/goby/compiler.Fuzz(0x7f9250bde000, 0x7, 0x7, 0x3)
	/home/user/go/src/github.com/goby-lang/goby/compiler/compiler_fuzz.go:10 +0x89
go-fuzz-dep.Main(0xc000049f80, 0x1, 0x1)
	/tmp/go-fuzz-build858729003/goroot/src/go-fuzz-dep/main.go:36 +0x1b6
main.main()
	/tmp/go-fuzz-build858729003/gopath/src/github.com/goby-lang/goby/compiler/go.fuzz.main/main.go:15 +0x52
exit status 2
```

**Comment by st0012** [comment]
@bookmoons hey thanks for the hard work!! I'm new to this service and fuzzing test so I'm just curious about if it'd make sense to fuzzing test bytecode compilation. I mean, it's expected to crash if we run it with a random set of input.

**Comment by bookmoons** [comment]
>I'm just curious about if it'd make sense to fuzzing test bytecode compilation.

Great idea. Is there an example of usage? I will update.

**Comment by st0012** [comment]
> Great idea. Is there an example of usage? I will update.

Sorry that my words might be misleading. I meant it don't really make sense to me to fuzzy test on bytecode compilation.

I think it makes more sense to fuzzy test on the integration level: generating random Goby code and run it to see what happens. 

If we agree with my suggestion, you can use `vm.testEval` function like

https://github.com/goby-lang/goby/blob/899cbeb6c1a6cc255c9c6f451ed9c4d23085acfb/vm/integer_test.go#L7-L23


However, we rescue panics for the vm so you might need to do some update for that 🤔 .

**Comment by bookmoons** [comment]
I see what you mean, sorry for misinterpreting. Going to look this over.

**Comment by bookmoons** [comment]
It seems just right. Good call. I'm going to update.

**Comment by bookmoons** [comment]
Here's one possibility. I pushed an update that interprets the fuzz as a sequence of Goby tokens. So you're at least working with valid pieces of the language.

```go
// decodeSourceFuzz maps fuzz to Goby source code
func decodeSourceFuzz(fuzz []byte) (source string, ok bool) {
	var builder strings.Builder
	var value string
	for len(fuzz) > 0 {
		switch fuzz[0] {
		case 0:
			// Constant
			value, fuzz, ok = extractConstant(fuzz)
			if !ok {
				return "", false
			}
			builder.WriteString(value)
		case 1:
			// Ident
			value, fuzz, ok = extractIdent(fuzz)
			if !ok {
				return "", false
			}
			builder.WriteString(value)
```

It's kind of tough to handle the whole syntax. You'd have to write a fuzzer that has syntax knowledge.

Fuzzit is using [go-fuzz](https://github.com/dvyukov/go-fuzz). It's one of these genetic fuzzers. It instruments your binary to detect branches then uses that to decide what to mutate and what to keep the same. Kind of like natural selection. It tries to evolve knowledge about your program. So the idea is you can let it learn your program automatically and you don't need to spend time on writing a custom fuzzer.

What do you think about it?

In `VM.ExecInstructions()` panics seem to be caught for `NormalMode` parsing. I've tried to get around this by using `TestMode` parsing. If I read the code correctly I think it lets panics through.

**Comment by st0012** [comment]
> In VM.ExecInstructions() panics seem to be caught for NormalMode parsing. I've tried to get around this by using TestMode parsing. If I read the code correctly I think it lets panics through.

Yes, we want parsing errors to be raised during tests but not under normal usages.

> Fuzzit is using go-fuzz. It's one of these genetic fuzzers. It instruments your binary to detect branches then uses that to decide what to mutate and what to keep the same. Kind of like natural selection. It tries to evolve knowledge about your program. So the idea is you can let it learn your program automatically and you don't need to spend time on writing a custom fuzzer.

I saw the hard work you've done, really appreciate it 🙇 . However I do wonder if we'll need to build such powerful tool for fuzzy testing on syntax. I didn't change my mind since my previous comment. But I didn't expect it to be this complicated.

Currently Goby is in an awkward state: It's mature enough to play with but also quite far from being helpful. So we do have a lot syntax related issues that's uncovered. But using this fuzzy testing approach seems to be an overkill. And the effort of maintaing it may costs more than the benefit we get from it.

Again, I'm sorry that I didn't understand fuzzy testing enough to see this coming 🙇 . But I don't think Goby is ready to adapt such complex tool yet.

**Comment by bookmoons** [comment]
Thank you kindly @st0012 for looking it over and explaining your thoughts here.

If it could generate valid Goby code would you consider? I have some ideas about how to do it. If it's possible I can investigate.

**Comment by bookmoons** [comment]
Looks like I'm going to be pulled away for a while, so I have to withdraw this submission. Thank you for considering and discussing @st0012.

**Pull request closed without merging**
