### PR TITLE
Prohibit module inheritance

### PR DESCRIPTION
**Pull request by hachi8833**
(see #119 )
Sorry for the delay. I'd be glad if some of you'd take a look at the fix. 

Test code for the fix is still needed. 
I'd add the test when #133 is merged to master.

### CODE REVIEW

**Comment by hachi8833** [comment]
I'm unsure how to add a flag to codecov coverage...

**Comment by adlerhsieh** [comment]
Could you also add a test for this case? The reason why codecov does not pass is because we add some code without giving a test case (which decrease the % of coverage).

You can add a case in `vm/class_test.go` like:

```go
func TestClassInheritModule(t *testing.T) {
  input := `
module Foo
end

class Bar < Foo
end
`

  evaluated := testEval(t, input)
  // check if `evaluated` is an error or contains error message
}
```

You can find several examples for testing errors in the same file. 

Make sure it pass and push again :)

**Comment by st0012** [comment]
LGTM
@adlerhsieh You can merge it once you reviewed.

**Comment by adlerhsieh** [comment]
Looks good. Thanks!

**Pull request merged**
