### PR TITLE
Add Go 1.13.x to .travis.yml

### PR DESCRIPTION
**Pull request by hachi8833**
Drop 'trusty' from the yaml https://github.com/travis-ci/travis-ci/issues/9928

### CODE REVIEW

**Comment by hachi8833** [comment]
Umm..., let me try reducing the matrix.

**Comment by hachi8833** [comment]
I found that I haven't fetched the latest master branch 😓 and this caused the travis errors. Sorry for the frequent push 🙇

**Comment by st0012** [comment]
@hachi8833 I think the failures are caused by randomly happened race condition issue? It's been there for a while, I should fix it 😓

**Comment by hachi8833** [comment]
Thank you for the reply!
The behavior of travis might contain a kind of randomization...?

**Comment by hachi8833** [comment]
Confirmed #778 works fine on the branch!
I reverted the temporal change to be merged.
I guess merging #778 to this #777 first and then merging #777 to master is good. Shall I do this or will you do this? @st0012

**Comment by hachi8833** [comment]
Finally pushed the branch with the master merged.

**Comment by st0012** [comment]
@hachi8833 thank you for the work!

**Pull request merged**
