### PR TITLE
Improve error handling

### PR DESCRIPTION
**Pull request by st0012**
I changed the vm's error handling to have the following behaviors:

### Normal mode
- Goby error 
	- return error object 
	- show stack traces
	- exit program with status 1
- Go panic - panic
### Test mode
- Goby error 
	- return error object
- Go panic - panic
### REPL mode
- Goby error
	- return error object
	- show stack traces
- Go panic - panic

### CODE REVIEW

**Comment by st0012** [comment]
@hachi8833 can you help me confirm the behavior? You can put something like
```go
fmt.Print(args[100])
```
in the instructions to create panic

**Comment by hachi8833** [comment]
I'll check this

**Comment by hachi8833** [comment]
Checked with `fmt.Print(args[100])` for intentional panics against the following instructions and works all as expected!

```
47:		name: bytecode.Pop,
53:		name: bytecode.Dup,
60:		name: bytecode.PutObject,
67:		name: bytecode.PutObject,
74:		name: bytecode.GetConstant,
93:		name: bytecode.GetLocal,
109:		name: bytecode.GetInstanceVariable,
123:		name: bytecode.SetInstanceVariable,
146:		name: bytecode.SetLocal,
184:		name: bytecode.SetConstant,
198:		name: bytecode.NewRange,
207:		name: bytecode.NewArray,
222:		name: bytecode.ExpandArray,
250:		name: bytecode.SplatArray,
263:		name: bytecode.NewHash,
279:		name: bytecode.BranchUnless,
304:		name: bytecode.BranchIf,
325:		name: bytecode.Jump,
331:		name: bytecode.Break,
355:		name: bytecode.PutSelf,
361:		name: bytecode.PutString,
368:		name: bytecode.PutFloat,
382:		name: bytecode.PutNull,
388:		name: bytecode.DefMethod,
410:		name: bytecode.DefSingletonMethod,
431:		name: bytecode.DefClass,
477:		name: bytecode.Send,
551:		name: bytecode.InvokeBlock,
608:		name: bytecode.GetBlock,
626:		name: bytecode.Leave,
```

**Comment by hachi8833** [comment]
It was a good experience digging into instruction codes 😄

**Pull request merged**
