### PR TITLE
REPL: Change `restart` command to `reset` for simplification

### PR DESCRIPTION
**Pull request by hachi8833**
* `restart` command to `reset`
* Just added the following fortune when starting/resetting/exiting REPL. I just wonder it is OK for you.

image

### CODE REVIEW

**Comment by st0012** [comment]
@hachi8833 Haha it's pretty funny, LGTM. But I think it's better to separate those emojis into categories, and display them according to the command. For example, only put positive emoji when REPL started.

**Comment by hachi8833** [comment]
Thanks!
It'd be better you modify the behavior as you like.

**Comment by st0012** [comment]
You should make the final decision on this, it's just a suggestion 😁

**Comment by hachi8833** [comment]
Perhaps I'd arrange in a bit unobtrusive way: showing this only once would be nicer.

**Comment by hachi8833** [comment]
Modified the fortune a bit.
In addition, I made the package variables to func variables in REPL.

**Pull request merged**
